# insert some test values into db

libraries = DB[:libraries]
if libraries.count < 1
selections = DB[:selections]
datasets = DB[:sequencing_datasets]
peptides = DB[:peptides]
clusters = DB[:clusters]
dnas = DB[:dna_sequences]
targets = DB[:targets]
results = DB[:results]
clupeps = DB[:clusters_peptides] 
pepseqs = DB[:peptides_sequencing_datasets]
dnapepseqs = DB[:dna_sequences_peptides_sequencing_datasets]


targets.insert(:species => 'mouse', :tissue => 'lung', :cell => 'A')
targets.insert(:species => 'horse', :tissue => 'heart', :cell => 'B')
targets.insert(:species => 'mouse', :tissue => 'liver', :cell => 'D')
targets.insert(:species => 'mouse', :tissue => 'brain', :cell => 'C')

libraries.insert(:library_name => 'lib1', :encoding_scheme => 'NNN', :carrier => 'mouse', :produced_by => 'me', :date => Date.today, :insert_length => 7, :peptide_diversity => 0.542, :distinct_peptides => 0)
libraries.insert(:library_name => 'lib2', :encoding_scheme => 'NNK', :carrier => 'mouse', :produced_by => 'me', :date => Date.today, :insert_length => 7, :peptide_diversity => 0.987, :distinct_peptides => 0 )

selections.insert(:selection_name => 'sel1', :date => Date.today+1, :library_name => 'lib1', :target_id => 1)
selections.insert(:selection_name => 'sel2', :date => Date.today+2, :library_name => 'lib1', :target_id => 2)
selections.insert(:selection_name => 'sel3', :date => Date.today+3, :library_name => 'lib2', :target_id => 3)
selections.insert(:selection_name => 'sel4', :date => Date.today+1, :library_name => 'lib2', :target_id => 4)

datasets.insert(:dataset_name => "ds1", :read_type => 'partial', :used_indices => 'BWERT', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib1', :selection_name => 'sel1', :target_id => 2)
datasets.insert(:dataset_name => "ds2", :read_type => 'partial', :used_indices => 'BWQERWEr', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib1', :selection_name => 'sel1', :target_id =>1)
datasets.insert(:dataset_name => "ds3", :read_type => 'partial', :used_indices => 'GBEWWR', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib1', :selection_name => 'sel2', :target_id => 4)
datasets.insert(:dataset_name => "ds4", :read_type => 'partial', :used_indices => 'SGSWER', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib1', :selection_name => 'sel2', :target_id => 3)
datasets.insert(:dataset_name => "ds5", :read_type => 'partial', :used_indices => 'BERWR', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib2', :selection_name => 'sel3', :target_id => 2)
datasets.insert(:dataset_name => "ds6", :read_type => 'partial', :used_indices => 'SDBWF', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib2', :selection_name => 'sel3',:target_id => 4)
datasets.insert(:dataset_name => "ds7", :read_type => 'partial', :used_indices => 'ASDVV', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib2', :selection_name => 'sel4', :target_id => 2)
datasets.insert(:dataset_name => "ds8", :read_type => 'partial', :used_indices => 'APOQEW', :origin => 'elephant', :produced_by => 'me', :sequencer => 'ngs', :date => Date.today-5, :selection_round => 4, :sequence_length => 3, :library_name => 'lib2', :selection_name => 'sel4', :target_id => 1)

peptides.insert(:peptide_sequence => 'AVGDERT')
peptides.insert(:peptide_sequence => 'CVEWRRF')
peptides.insert(:peptide_sequence => 'FGBEWTE')
peptides.insert(:peptide_sequence => 'DBERGET')
peptides.insert(:peptide_sequence => 'DFGWERR')
peptides.insert(:peptide_sequence => 'ERTGWEG')
peptides.insert(:peptide_sequence => 'EDFGWEE')
peptides.insert(:peptide_sequence => 'NFBWERR')
peptides.insert(:peptide_sequence => 'WERVSDF')
peptides.insert(:peptide_sequence => 'BDFWERF')
peptides.insert(:peptide_sequence => 'WERVERG')
peptides.insert(:peptide_sequence => 'ERGWERR')
peptides.insert(:peptide_sequence => 'BERGERR')
peptides.insert(:peptide_sequence => 'ERTWERR')
peptides.insert(:peptide_sequence => 'HWRTERT')
peptides.insert(:peptide_sequence => 'ERFGWER')
peptides.insert(:peptide_sequence => 'WERFWET')
peptides.insert(:peptide_sequence => 'EWRGEWE')
peptides.insert(:peptide_sequence => 'WERVADR')
peptides.insert(:peptide_sequence => 'WERAGER')
peptides.insert(:peptide_sequence => 'WERWERG')
peptides.insert(:peptide_sequence => 'NRTZHWE')

clusters.insert(:parameters => 'droelf', :consensus_sequence => 'SDAFA', :library_name => 'lib1', :selection_name => 'sel1', :dataset_name => 'ds1')
clusters.insert(:parameters => 'droelf', :consensus_sequence => 'SDAFA', :library_name => 'lib1', :selection_name => 'sel2', :dataset_name => 'ds3')
clusters.insert(:parameters => 'droelf', :consensus_sequence => 'SDAFA', :library_name => 'lib1', :selection_name => 'sel2', :dataset_name => 'ds4')
clusters.insert(:parameters => 'droelf', :consensus_sequence => 'SDAFA', :library_name => 'lib2', :selection_name => 'sel3', :dataset_name => 'ds6')
clusters.insert(:parameters => 'droelf', :consensus_sequence => 'SDAFA', :library_name => 'lib2', :selection_name => 'sel4', :dataset_name => 'ds7')

dnas.insert(:dna_sequence => 'ACTCTGTACTTACTCATGACTAGCGACG')
dnas.insert(:dna_sequence => 'ACTATCGATCGATCGACTTGCAGCGACG')
dnas.insert(:dna_sequence => 'ACGTAGCATGCTAGCTAGCTAGCTAGCG')
dnas.insert(:dna_sequence => 'ACGAGTCAGTCAGCATGCTAGCATCGAT')
dnas.insert(:dna_sequence => 'ACGATCGATGCATCGATCGATCGACTAG')
dnas.insert(:dna_sequence => 'ACCGGATCGATCAGCTAGTCAGCTAGCT')
dnas.insert(:dna_sequence => 'AGATCGACGACTAGCTAGCTAGCTAGCT')
dnas.insert(:dna_sequence => 'ACGGTACGATCGATCGATCGATCGATCT')
dnas.insert(:dna_sequence => 'ACGGATCGATCGATGCTCGATCGATCGA')
dnas.insert(:dna_sequence => 'AGGATCGATCAGCTAGCTAGCTAGCTTA')
dnas.insert(:dna_sequence => 'ACTCTGTACGTAGCTACGACTTTACGAT')
dnas.insert(:dna_sequence => 'ACTCTCGGCGCGATATCATCTGGATATA')
dnas.insert(:dna_sequence => 'ACTCTGACGAGCATCTACTACAGCATAT')
dnas.insert(:dna_sequence => 'ACGACGGTACTACTGTACTACTACAGCA')
dnas.insert(:dna_sequence => 'AGGTACATACTACGACGCAGCATCATCT')
dnas.insert(:dna_sequence => 'ACTGATCGACTGATCGATCGATCAGTCT')
dnas.insert(:dna_sequence => 'ACTGATCGATCGTACGTACGATCGTACG')
dnas.insert(:dna_sequence => 'ACTAGTCAGCTAGCTAGCTAGCTACGAT')
dnas.insert(:dna_sequence => 'ATGCGGATCGATCGATCGATCGATCGAT')
dnas.insert(:dna_sequence => 'AGGATCGATCGATCGATCGATCGATCGA')
dnas.insert(:dna_sequence => 'ACGGACTAGCTAGCTAGCTAGCTAGCTA')
dnas.insert(:dna_sequence => 'ACTCGGATCGATCGATCGATCGATCAGT')
dnas.insert(:dna_sequence => 'ACTCTGTACTACGTACGATCGATCGATC')
dnas.insert(:dna_sequence => 'ACTCTGTAGCTACTACGACTACGACTAC')
dnas.insert(:dna_sequence => 'GCCGGATCGATCGATCGACTAGCTAGCA')
dnas.insert(:dna_sequence => 'ACGGTACTACTACTATATATTACGGCTA')
dnas.insert(:dna_sequence => 'ACGGCGCGATCGATCGATCGATCATATC')
dnas.insert(:dna_sequence => 'ACGACGGCGATATTCGCCCCTACTAGCT')
dnas.insert(:dna_sequence => 'ACTCTACGACTACTGGCGCGTATATATA')
dnas.insert(:dna_sequence => 'ACTCGGACTAGTCAGTCAGTCATTATAC')
dnas.insert(:dna_sequence => 'ACTCGGCTAGCTAGCTATTATCGACTAC')
dnas.insert(:dna_sequence => 'CTTAGGCAGCTACTATCATCATCTCGGC')
dnas.insert(:dna_sequence => 'ACTCTGCATCGATGCATACGTATCAGCT')
dnas.insert(:dna_sequence => 'ACGCTAGCTAGCTAGCTACGATCATCAT')
dnas.insert(:dna_sequence => 'ACGCGAGTCATCATCGACAGCAGCATCA')
dnas.insert(:dna_sequence => 'GGCATCGATCGATCATCTATATATATAC')
dnas.insert(:dna_sequence => 'CGCGCGCGATTATCTCTCTCAATAACTT')
dnas.insert(:dna_sequence => 'TAGCGACGCAGCGATCGACTAGCTAGCT')
dnas.insert(:dna_sequence => 'CTAGCGACGGACTGATCATATCGCGCTA')
dnas.insert(:dna_sequence => 'CGACTGATCATACTACTGACTGACTAGG')
dnas.insert(:dna_sequence => 'CGGCATCGTACGATCGATCGATCGATCA')
dnas.insert(:dna_sequence => 'AGCGACGGTACATCGATCGATCGACATC')
dnas.insert(:dna_sequence => 'CGACGGATCTATATATCGCGCACTTTTA')
dnas.insert(:dna_sequence => 'ACTCTGACTACTATCATCTACTATCATC')



results.insert(:performance => 'super', :target_id =>1) 
results.insert(:performance => '--', :target_id =>2) 
results.insert(:performance => 'schlecht', :target_id =>3) 
results.insert(:performance => 'super', :target_id =>1) 
results.insert(:performance => 'top', :target_id =>4) 
results.insert(:performance => 'lahm', :target_id =>4) 

clupeps.insert(:cluster_id => '1', :peptide_sequence => 'EDFGWEE')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'BDFWERF')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'DFGWERR')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'WERVSDF')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'HWRTERT')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'NRTZHWE')
clupeps.insert(:cluster_id => '1', :peptide_sequence => 'DBERGET')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'WERAGER')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'WERFWET')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'BDFWERF')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'WERVSDF')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'DFGWERR')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'HWRTERT')
clupeps.insert(:cluster_id => '2', :peptide_sequence => 'CVEWRRF')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'DBERGET')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'CVEWRRF')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'AVGDERT')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'WERVSDF')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'WERAGER')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'BDFWERF')
clupeps.insert(:cluster_id => '3', :peptide_sequence => 'ERFGWER')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'CVEWRRF')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'NRTZHWE')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'WERAGER')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'WERFWET')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'DBERGET')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'ERFGWER')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'HWRTERT')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'EDFGWEE')
clupeps.insert(:cluster_id => '4', :peptide_sequence => 'DFGWERR')

pepseqs.insert(:dataset_name => 'ds1', :peptide_sequence => 'AVGDERT', :rank => 2, :reads => 10, :dominance => 0.123, :result_id => 1)
pepseqs.insert(:dataset_name => 'ds1', :peptide_sequence => 'FGBEWTE', :rank => 12, :reads => 234, :dominance => 0.325)
pepseqs.insert(:dataset_name => 'ds1', :peptide_sequence => 'DFGWERR', :rank => 465, :reads => 2134214, :dominance => 0.756)
pepseqs.insert(:dataset_name => 'ds1', :peptide_sequence => 'EDFGWEE', :rank => 214, :reads => 10, :dominance => 0.235)
pepseqs.insert(:dataset_name => 'ds1', :peptide_sequence => 'NFBWERR', :rank => 24, :reads => 3245, :dominance => 0.1234)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'ERTGWEG', :rank => 7, :reads => 21314, :dominance => 0.456)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'DBERGET', :rank => 234, :reads => 123, :dominance => 0.57)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'WERVSDF', :rank => 4537, :reads => 214321, :dominance => 0.578)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'BDFWERF', :rank => 6, :reads => 214, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'AVGDERT', :rank => 234, :reads => 1234214, :dominance => 0.34)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'WERVERG', :rank => 2, :reads => 1234, :dominance => 0.26)
pepseqs.insert(:dataset_name => 'ds2', :peptide_sequence => 'CVEWRRF', :rank => 4, :reads => 124, :dominance => 0.37)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'ERGWERR', :rank => 24, :reads => 123, :dominance => 0.246)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'ERTWERR', :rank => 2, :reads => 10123, :dominance => 0.6578)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'BDFWERF', :rank => 34, :reads => 123, :dominance => 0.8)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'EDFGWEE', :rank => 436, :reads => 2134, :dominance => 0.37)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'DFGWERR', :rank => 4357, :reads => 2134, :dominance => 0.3254)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'HWRTERT', :rank => 457, :reads => 1234, :dominance => 0.2352, :result_id => 2)
pepseqs.insert(:dataset_name => 'ds3', :peptide_sequence => 'WERFWET', :rank => 7, :reads => 1243, :dominance => 0.3254)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'ERTWERR', :rank => 2, :reads => 10, :dominance => 0.35)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'CVEWRRF', :rank => 1234, :reads => 2134, :dominance => 0.5687)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'EWRGEWE', :rank => 2, :reads => 1234, :dominance => 0.4)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'ERGWERR', :rank => 2, :reads => 10, :dominance => 0.32)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'FGBEWTE', :rank => 2, :reads => 2143, :dominance => 0.8)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'ERTGWEG', :rank => 13, :reads => 10, :dominance => 0.325)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'WERFWET', :rank => 437, :reads => 3254, :dominance => 0.5467)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'DFGWERR', :rank => 2, :reads => 23453245, :dominance => 0.658)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'EDFGWEE', :rank => 4375, :reads => 2143, :dominance => 0.12473)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'HWRTERT', :rank => 123, :reads => 123, :dominance => 0.5687)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'BERGERR', :rank => 2, :reads => 3457, :dominance => 0.325)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'WERVSDF', :rank => 1234, :reads => 437, :dominance => 0.6578)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'AVGDERT', :rank => 4357, :reads => 1234, :dominance => 0.5678)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'BDFWERF', :rank => 2, :reads => 632, :dominance => 0.2345)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'DBERGET', :rank => 2, :reads => 3452, :dominance => 0.5476, :result_id => 3)
pepseqs.insert(:dataset_name => 'ds4', :peptide_sequence => 'WERVERG', :rank => 123, :reads => 1234, :dominance => 0.3245)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'CVEWRRF', :rank => 4357, :reads => 2134, :dominance => 0.1324523)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'ERTGWEG', :rank => 234, :reads =>210, :dominance => 0.3245)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'DFGWERR', :rank => 2, :reads => 1235, :dominance => 0.854)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'EDFGWEE', :rank => 124, :reads => 1234, :dominance => 0.57)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'DBERGET', :rank => 457, :reads => 125, :dominance => 0.5467)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'NFBWERR', :rank => 457, :reads => 2134, :dominance => 0.547)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'BERGERR', :rank => 4747, :reads => 1234, :dominance => 0.845)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'AVGDERT', :rank => 123, :reads => 3264, :dominance => 0.453467)
pepseqs.insert(:dataset_name => 'ds5', :peptide_sequence => 'WERFWET', :rank => 325, :reads => 3246, :dominance => 0.235, :result_id => 4)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'CVEWRRF', :rank => 123, :reads => 51235, :dominance => 0.235)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'ERTGWEG', :rank => 235, :reads => 2134, :dominance => 0.3254)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'FGBEWTE', :rank => 326232, :reads => 1234, :dominance => 0.2345)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'NFBWERR', :rank => 123, :reads => 346, :dominance => 0.3254)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'BERGERR', :rank => 123, :reads => 2134, :dominance => 0.5467)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'EDFGWEE', :rank => 236, :reads => 2364, :dominance => 0.4567)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'DFGWERR', :rank => 453734, :reads => 2364236, :dominance => 0.547)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'WERVSDF', :rank => 123, :reads => 236324, :dominance => 0.5467)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'ERGWERR', :rank => 234, :reads => 23642346, :dominance => 0.567)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'EWRGEWE', :rank => 123, :reads => 1234, :dominance => 0.456)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'WERVADR', :rank => 123, :reads => 3262346, :dominance => 0.4576)
pepseqs.insert(:dataset_name => 'ds6', :peptide_sequence => 'BDFWERF', :rank => 4357, :reads => 3632, :dominance => 0.54)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'DBERGET', :rank => 36, :reads => 3246326, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'ERTGWEG', :rank => 123, :reads => 12363260, :dominance => 0.345, :result_id => 5)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'CVEWRRF', :rank => 123, :reads => 3262346, :dominance => 0.3245)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'WERWERG', :rank => 73, :reads => 234623, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'ERGWERR', :rank => 234, :reads => 2364, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'HWRTERT', :rank => 123, :reads => 36326, :dominance => 0.4)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'AVGDERT', :rank => 35, :reads => 3246236, :dominance => 0.123)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'BERGERR', :rank => 123, :reads => 3463246, :dominance => 0.3456)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'WERVSDF', :rank => 35, :reads => 34636, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'WERVERG', :rank => 234, :reads => 161, :dominance => 0.3425)
pepseqs.insert(:dataset_name => 'ds7', :peptide_sequence => 'WERFWET', :rank => 4365, :reads => 3246236, :dominance => 0.3456)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'NFBWERR', :rank => 457, :reads => 125, :dominance => 0.325)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'FGBEWTE', :rank => 123, :reads => 1243, :dominance => 0.234)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'HWRTERT', :rank => 354, :reads => 235, :dominance => 0.345)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'ERGWERR', :rank => 465, :reads => 236, :dominance => 0.234)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'ERTWERR', :rank => 456, :reads => 2134, :dominance => 0.34535, :result_id => 6)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'BERGERR', :rank => 123, :reads => 3246, :dominance => 0.243)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'WERVERG', :rank => 4646, :reads => 124, :dominance => 0.3456)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'DBERGET', :rank => 345, :reads => 214, :dominance => 0.234)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'CVEWRRF', :rank => 4356, :reads => 36, :dominance => 0.354)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'WERVSDF', :rank => 243, :reads => 2143, :dominance => 0.234)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'ERTGWEG', :rank => 214, :reads => 3245, :dominance => 0.234)
pepseqs.insert(:dataset_name => 'ds8', :peptide_sequence => 'AVGDERT', :rank => 123, :reads => 3245, :dominance => 0.234)

dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 764 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACGGATCGATCGATGCTCGATCGATCGA', :reads => 1456560 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGGTACGATCGATCGATCGATCGATCT', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTCTGACGAGCATCTACTACAGCATAT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACTGATCGACTGATCGATCGATCAGTCT', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 75676 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTAGTCAGCTAGCTAGCTAGCTACGAT', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'AGGTACATACTACGACGCAGCATCATCT', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'NFBWERR', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'AGGATCGATCGATCGATCGATCGATCGA', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'NFBWERR', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTCTGTACTACGTACGATCGATCGATC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCTGTAGCTACTACGACTACGACTAC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCTACGACTACTGGCGCGTATATATA', :reads => 17897890 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGGACTAGCTAGCTAGCTAGCTAGCTA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds1', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACGGCGCGATCGATCGATCGATCATATC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'GCCGGATCGATCGATCGACTAGCTAGCA', :reads => 89 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACTCTGCATCGATGCATACGTATCAGCT', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVERG', :dna_sequence =>'CGACTGATCATACTACTGACTGACTAGG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTCGGATCGATCGATCGATCGATCAGT', :reads => 10774 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'AGGATCGATCGATCGATCGATCGATCGA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 78 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'BDFWERF', :dna_sequence =>'CTTAGGCAGCTACTATCATCATCTCGGC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 7267 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGGATCGATCGATGCTCGATCGATCGA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVERG', :dna_sequence =>'AGGTACATACTACGACGCAGCATCATCT', :reads => 1890 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 789789 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 77 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVERG', :dna_sequence =>'CGACGGATCTATATATCGCGCACTTTTA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCTGCATCGATGCATACGTATCAGCT', :reads => 123 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACTCTCGGCGCGATATCATCTGGATATA', :reads => 456453 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 7897 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTCTACGACTACTGGCGCGTATATATA', :reads => 4564 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'AVGDERT', :dna_sequence =>'AGGTACATACTACGACGCAGCATCATCT', :reads => 786786 )
dnapepseqs.insert(:dataset_name => 'ds2', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads =>  456456)
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERTWERR', :dna_sequence =>'CTTAGGCAGCTACTATCATCATCTCGGC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 78 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACGGTACTACTACTATATATTACGGCTA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACGGCGCGATCGATCGATCGATCATATC', :reads => 789789 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'HWRTERT', :dna_sequence =>'GCCGGATCGATCGATCGACTAGCTAGCA', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'BDFWERF', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACGGTACGATCGATCGATCGATCGATCT', :reads => 786456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACTAGTCAGCTAGCTAGCTAGCTACGAT', :reads => 4524 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERGWERR', :dna_sequence =>'AGGATCGATCGATCGATCGATCGATCGA', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 6786 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTCTGTACTACGTACGATCGATCGATC', :reads => 789463 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGACGGCGATATTCGCCCCTACTAGCT', :reads => 45 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 897 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'CGACTGATCATACTACTGACTGACTAGG', :reads => 14564560 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGGACTAGCTAGCTAGCTAGCTAGCTA', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'AGCGACGGTACATCGATCGATCGACATC', :reads => 178978960 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERGWERR', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 178970 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTGATCGACTGATCGATCGATCAGTCT', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 14564560 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 789789 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 897 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 56456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'BDFWERF', :dna_sequence =>'AGCGACGGTACATCGATCGATCGACATC', :reads => 123123 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGGATCGATCGATGCTCGATCGATCGA', :reads => 786 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 456456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTCTGTAGCTACTACGACTACGACTAC', :reads => 789 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACGGTACGATCGATCGATCGATCGATCT', :reads => 4534 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'BDFWERF', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 453435 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'AGGTACATACTACGACGCAGCATCATCT', :reads => 456 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'WERFWET', :dna_sequence =>'AGGATCGATCGATCGATCGATCGATCGA', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'CGACTGATCATACTACTGACTGACTAGG', :reads => 32 )
dnapepseqs.insert(:dataset_name => 'ds3', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACGACGGCGATATTCGCCCCTACTAGCT', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EWRGEWE', :dna_sequence =>'CGACTGATCATACTACTGACTGACTAGG', :reads => 364 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTCTGCATCGATGCATACGTATCAGCT', :reads => 2342 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACTCTGTACTACGTACGATCGATCGATC', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EWRGEWE', :dna_sequence =>'ACTAGTCAGCTAGCTAGCTAGCTACGAT', :reads => 3456 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTCTCGGCGCGATATCATCTGGATATA', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTCTACGACTACTGGCGCGTATATATA', :reads => 2342 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 64356 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'CTTAGGCAGCTACTATCATCATCTCGGC', :reads => 452 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EWRGEWE', :dna_sequence =>'ACGACGGTACTACTGTACTACTACAGCA', :reads => 234234 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 3463246 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EWRGEWE', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGGTACTACTACTATATATTACGGCTA', :reads => 3463 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'BERGERR', :dna_sequence =>'AGGTACATACTACGACGCAGCATCATCT', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 346326 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACGCGAGTCATCATCGACAGCAGCATCA', :reads => 34632 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACGCTAGCTAGCTAGCTACGATCATCAT', :reads => 3452345 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'GGCATCGATCGATCATCTATATATATAC', :reads => 3425 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERGWERR', :dna_sequence =>'GCCGGATCGATCGATCGACTAGCTAGCA', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 72357 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACGGACTAGCTAGCTAGCTAGCTAGCTA', :reads => 72457 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'GGCATCGATCGATCATCTATATATATAC', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACTCGGATCGATCGATCGATCGATCAGT', :reads => 32466 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 457 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 4578 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTGATCGACTGATCGATCGATCAGTCT', :reads => 63456 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGGACTAGCTAGCTAGCTAGCTAGCTA', :reads => 834576 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 743754 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 324536 )
dnapepseqs.insert(:dataset_name => 'ds4', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 36474 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGGATCGATCGATGCTCGATCGATCGA', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ATGCGGATCGATCGATCGATCGATCGAT', :reads => 234 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGCTAGCTAGCTAGCTACGATCATCAT', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGCGAGTCATCATCGACAGCAGCATCA', :reads => 324 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 34622346 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACTCTGACGAGCATCTACTACAGCATAT', :reads => 32463246 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTCTGCATCGATGCATACGTATCAGCT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGACGGCGATATTCGCCCCTACTAGCT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 3643 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTCTGTAGCTACTACGACTACGACTAC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTCTCGGCGCGATATCATCTGGATATA', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACGGCGCGATCGATCGATCGATCATATC', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'NFBWERR', :dna_sequence =>'ACGCGAGTCATCATCGACAGCAGCATCA', :reads => 34 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'NFBWERR', :dna_sequence =>'CGACTGATCATACTACTGACTGACTAGG', :reads => 140 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'NFBWERR', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'NFBWERR', :dna_sequence =>'CGACGGATCTATATATCGCGCACTTTTA', :reads => 42 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'BERGERR', :dna_sequence =>'GCCGGATCGATCGATCGACTAGCTAGCA', :reads => 243 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTCTGTACTACGTACGATCGATCGATC', :reads => 3642346 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACGGTACGATCGATCGATCGATCGATCT', :reads => 234 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'AVGDERT', :dna_sequence =>'CGCGCGCGATTATCTCTCTCAATAACTT', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACGCTAGCTAGCTAGCTACGATCATCAT', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'WERFWET', :dna_sequence =>'CTTAGGCAGCTACTATCATCATCTCGGC', :reads => 10 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'WERFWET', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 62 )
dnapepseqs.insert(:dataset_name => 'ds5', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'WERVADR', :dna_sequence =>'ACTCTACGACTACTGGCGCGTATATATA', :reads => 10436 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTCTGACGAGCATCTACTACAGCATAT', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'EWRGEWE', :dna_sequence =>'ATGCGGATCGATCGATCGATCGATCGAT', :reads => 3463246 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 34 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 354 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'DFGWERR', :dna_sequence =>'ACTCTGTACTTACTCATGACTAGCGACG', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'DFGWERR', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 346 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGACGGTACTACTGTACTACTACAGCA', :reads => 6 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'EDFGWEE', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 6346 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACGGACTAGCTAGCTAGCTAGCTAGCTA', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'NFBWERR', :dna_sequence =>'ACTAGTCAGCTAGCTAGCTAGCTACGAT', :reads => 345 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 234 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGGCGCGATCGATCGATCGATCATATC', :reads => 132463240 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGGTACTACTACTATATATTACGGCTA', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTCTGTAGCTACTACGACTACGACTAC', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 634632 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 4537 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 45747 )
dnapepseqs.insert(:dataset_name => 'ds6', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 537437 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 437 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'WERWERG', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 326 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'WERWERG', :dna_sequence =>'ACGACGGTACTACTGTACTACTACAGCA', :reads => 23463246 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 4536 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 83 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 4357 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 3245 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'ERGWERR', :dna_sequence =>'ACTGATCGACTGATCGATCGATCAGTCT', :reads => 457 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 4357 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'AVGDERT', :dna_sequence =>'ACTCGGCTAGCTAGCTATTATCGACTAC', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACTCGGACTAGTCAGTCAGTCATTATAC', :reads => 2346 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACTCTGTACTACGTACGATCGATCGATC', :reads => 34262326 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'HWRTERT', :dna_sequence =>'GCCGGATCGATCGATCGACTAGCTAGCA', :reads => 2365 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACTCGGATCGATCGATCGATCGATCAGT', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACGACGGCGATATTCGCCCCTACTAGCT', :reads => 3426 )
dnapepseqs.insert(:dataset_name => 'ds7', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 62346 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACGGTACTACTACTATATATTACGGCTA', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACGATCGATGCATCGATCGATCGACTAG', :reads => 32535 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVSDF', :dna_sequence =>'ACTCTGACGAGCATCTACTACAGCATAT', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACGTAGCATGCTAGCTAGCTAGCTAGCG', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'ERTWERR', :dna_sequence =>'ACTAGTCAGCTAGCTAGCTAGCTACGAT', :reads => 3246326 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'DBERGET', :dna_sequence =>'ACTCTGTAGCTACTACGACTACGACTAC', :reads => 235 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ACTCGGATCGATCGATCGATCGATCAGT', :reads => 2134234 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'CVEWRRF', :dna_sequence =>'ATGCGGATCGATCGATCGATCGATCGAT', :reads => 43754375 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVERG', :dna_sequence =>'ACTGATCGATCGTACGTACGATCGTACG', :reads => 10342574 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVERG', :dna_sequence =>'ACTCTGTACGTAGCTACGACTTTACGAT', :reads => 3254 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'WERVERG', :dna_sequence =>'ATGCGGATCGATCGATCGATCGATCGAT', :reads => 72 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGAGTCAGTCAGCATGCTAGCATCGAT', :reads => 327 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACTCTGACGAGCATCTACTACAGCATAT', :reads => 3246 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'HWRTERT', :dna_sequence =>'ACTGATCGACTGATCGATCGATCAGTCT', :reads => 234535 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'FGBEWTE', :dna_sequence =>'ACGACGGTACTACTGTACTACTACAGCA', :reads => 734 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACGGATCGATCGATGCTCGATCGATCGA', :reads => 34622346 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACTCTCGGCGCGATATCATCTGGATATA', :reads => 32426326 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'ERTGWEG', :dna_sequence =>'ACCGGATCGATCAGCTAGTCAGCTAGCT', :reads => 34262346 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'BERGERR', :dna_sequence =>'AGGATCGATCAGCTAGCTAGCTAGCTTA', :reads => 32463246 )
dnapepseqs.insert(:dataset_name => 'ds8', :peptide_sequence =>'BERGERR', :dna_sequence =>'ACTATCGATCGATCGACTTGCAGCGACG', :reads => 3246326 )
end
